default_language_version:
    python: python3.11

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: requirements-txt-fixer
-   repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
    -   id: black
        args:
            - "--line-length=120"
-   repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
    -   id: isort
        args:
            - "--line-length=120"
-   repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
    -   id: flake8
        args:
            - "--max-line-length=120"

# TODO fix that later
#-   repo: https://github.com/pre-commit/mirrors-mypy
#    rev: v1.0.0
#    hooks:
#    -   id: mypy
#        additional_dependencies:
#            - djangorestframework-stubs==1.8.0
#            - django-stubs==1.14.0
